### ISSUE TITLE
Upgrade the Cosmos SDK dependencies to v0.50

### ISSUE THREAD

**Issue by gislik** [noble-assets/adr36#2]
With the recent upgrade of the [monerium/module-noble](https://github.com/monerium/module-noble) to Cosmos SDK v0.50, this library needs to be upgraded to take full advantage of a simpler and cleaner library dependencies.

**Comment by johnletey** [comment]
@gislik Check out https://github.com/noble-assets/adr36/commit/a1725145caa5675e09b6fcf29564a141ae418ae9! Not on main yet but usable, and already used inside the module 😄

**Comment by gislik** [comment]
Thanks @johnletey ... you're always one step ahead of me. I was preparing a PR with minimal changes but going to note that a full-blown rewrite would be needed to future-proof the implementation. Amazing.

**Comment by gislik** [comment]
You can see the draft PR but I'd much rather use your [eden branch](https://github.com/noble-assets/adr36/tree/eden) as the basis for the PR.

**Comment by johnletey** [comment]
I've release the `eden` branch as [`v1.0.0-rc.0`](https://github.com/noble-assets/adr36/releases/tag/v1.0.0-rc.0)!

**Comment by gislik** [comment]
Great news.
